import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'College events Management System',
  description: 'Generated by create next app',
}

const Navbar = () => {
  return (
    <nav className="flex items-center justify-between flex-wrap bg-teal-500 p-6">
      <div className="flex items-center flex-shrink-0 text-white mr-6">
        <span className="font-semibold text-xl tracking-tight">
          College events Management System
        </span>
      </div>
    </nav>
  )
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (

    <html lang="en">
      
      <body className={inter.className}>{children}</body>
      
    </html>


  )
}
